### ISSUE TITLE
How can I search words like müßig?

### ISSUE THREAD

**Issue by jorgesumle** [radomirbosak/duden#53]
'ü', 'ö', 'ä' and 'ß' are problematic.

**Comment by radomirbosak** [comment]
The word `müßig` can be displayed with
```console
$ duden mueszig
```

This is because the duden page for the word is https://www.duden.de/rechtschreibung/mueszig

But I agree that the behavior not very intuitive.

A solution to this might be implementing https://github.com/radomirbosak/duden/issues/44 - the program will first search for the string "müßig" and display results for the first page found.

(Note that function `duden.get` displays an exact duden page, while `duden.search` performs search on a string via https://www.duden.de/suchen/dudenonline?s=&scope=all).

So I'll close this issue in favor of https://github.com/radomirbosak/duden/issues/44 .
