### ISSUE TITLE
Alternate spelling - Word not found

### ISSUE THREAD

**Issue by Scriptim** [radomirbosak/duden#58]
Searching for alternate spellings gives *Word not found*.

```
$ duden Differenzial
Differenzial, Differential, das
===============================
Word type: Substantiv, Neutrum
Commonness: 1/5
Separation: Dif|fe|ren|zi|al, Dif|fe|ren|ti|al
Meaning overview:
 0. (Mathematik) Zuwachs einer Funktion bei einer [kleinen] Änderung ihres Arguments (2)

 1. Kurzform für: Differenzialgetriebe
```

```
$ duden Differential
Word 'Differential' not found
```

**Comment by Scriptim** [comment]
The above example is from the current pypi release. With the actual version from this repo I get that error for both spellings.

**Comment by radomirbosak** [comment]
This is an interesting bug.

I'll be assuming the latest master-branch version. (releasing the newest version to pypi is tracked here https://github.com/radomirbosak/duden/issues/65)

The newest version does perform automatic search every time, but it also checks if the searched term matches the title on the search page. The matching fails for `duden Differenzial`, since the first matched word has the title `Differenzial, Differential` (`differenzial, differential` when searching for `Differential` with "T").

This is checked here:
https://github.com/radomirbosak/duden/blob/master/duden/main.py#L473

```python
...
        urlnames = [a['href'].split('/')[-1]
                    for a in a_tags
                    if (not exact) or clear_text(a.text) == word]
        if return_words:
            return [get(urlname) for urlname in urlnames]
        else:
    return urlnames
...
```
Btw. if you allow for fuzzy searching, you will definitely find something:
```
python3 run_duden.py Differential --fuzzy
Found 15 matching words. Use the -r/--result argument to specify which one to display.
1) differenzial
2) Differenziator
3) Differenziation
4) Differenzial
5) different
6) Differenzialrente
7) Differenzialgeometrie
8) Differenzialgetriebe
9) Differenzialrechnung
10) Differenzialgleichung
11) Differenzialschaltung
12) Differenzialdiagnose
13) Differenzialdiagnostik
14) Differenzialanalysator
15) Differenzialquotient
```
(note that the strings displayed here are the url parts corresponding to those words, not the search-page-link titles which are used for determining if the word matches the search term)

**Comment by radomirbosak** [comment]
So to resolve this, I think we can just split the word titles on the search page whenever we find a separating comma and check if the search term equals to *any* of the split parts.

**Comment by radomirbosak** [comment]
https://github.com/radomirbosak/duden/pull/66 resolves this.
